[package]
name = "von-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true }
von-core = { workspace = true }

[dev-dependencies]
tower = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
